name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build debug
        run: bash ./gradlew build jacocoTestReport assembleAndroidTest
      - name: run tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.3
        with:
          api-level: 25
          target: google_apis
          arch: x86_64
          cmd: ./gradlew connectedCheck
      - name: Upload coverage to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov
